#!/bin/sh
TUN_MODULE="/lib/modules/tun.ko"

eval $(env | grep "^SYNOPKG_PKGDEST=")
ret=`ln -s "${SYNOPKG_PKGDEST}/S2SVPN" /usr/syno/synoman/webman/3rdparty/EASYRSA`
ret=`chown -R admin.users $SYNOPKG_PKGDEST`
ret=`chmod +x /usr/syno/synoman/webman/3rdparty/EASYRSA/php-cli`
exit 0 