#!/bin/sh

case $1 in
	start)
		exit 0
	;;
	stop)
		exit 0
	;;
	status)
		exit 0
	;;
	log)
		echo "S2SVPN installed properly. To access it, click icon under 'admin' menu">/tmp/S2SVPN.log
		echo "/tmp/S2SVPN.log";
		exit 0
	;;
esac
                                     
