#!/bin/sh

case $1 in
	start)
		exit 0
	;;
	stop)
		exit 0
	;;
	status)
		exit 0
	;;
	log)
		echo "EasyRSA installed properly. To access it, click icon under 'admin' menu">/tmp/EasyRSA.log
		echo "/tmp/EasyRSA.log";
		exit 0
	;;
esac
                                     
